### ISSUE TITLE
En Training/Product Backlog screen, el Menu derecha se queda siempre desplegado after scroll-up

### ISSUE THREAD

**Issue by Cath2Bcn** [AlbertProfe/wiki#7]
En Training/Product Backlog/, el "on this page" menu de la derecha (fichero 1-) se contrae con el scroll-down (fichero 2-), pero a la minima que se hace un scroll-up, se desplega este menu por encima de la pagina, y no vuelve a contraerse (fichero 3-).
La unica manera que he encontrado es volver al inicio de la pagina para volver a hacer scroll-down.
¿Se podría controlar el desplegable del menu con el scroll-up?

<img width="1267" alt="1-menu-init OK" src="https://github.com/AlbertProfe/wiki/assets/154472312/0862e707-1413-49d0-b0f7-ba89ed350445">
<img width="1267" alt="2-menu-scroll-down OK" src="https://github.com/AlbertProfe/wiki/assets/154472312/6fa2ccf8-39e4-4d77-998a-f689c4e8e7fb">
<img width="1272" alt="3-menu scroll-up FAIL" src="https://github.com/AlbertProfe/wiki/assets/154472312/ba74a1b8-9541-42ac-9d57-6a2e3e72b779">

**Comment by AlbertProfe** [comment]
you are right, it is a quarto bug, very annoying, Next week we will work on it

Thanks

**Comment by AlbertProfe** [comment]
solved

[sprint](https://albertprofe.dev/ifcd0210-24/ifcd0210backlog-sprint-24.html)

**Comment by Cath2Bcn** [comment]
Ole! 👏👍
