### ISSUE TITLE
Desplegable de "ReactJS": palabra "props" invisible

### ISSUE THREAD

**Issue by Cath2Bcn** [AlbertProfe/wiki#9]
Hola,
En el desplegable del menu ReactJS, la palabra "props" no se ve en la opcion "props and state" (ver fichero adjunto).
Gracias,

![Screenshot from 2024-02-03 11-35-34](https://github.com/AlbertProfe/wiki/assets/154472312/5d167172-dc76-48e6-9815-5c9fae0925b4)

**Comment by AlbertProfe** [comment]
si, este es un clasico bug que aun no han resuelto

en el menu no se puede colocar texto code

lo dejo como texto plano

**Comment by Cath2Bcn** [comment]
👏👍
